### ISSUE TITLE
Compile Issue IAR EWARM v9.20.2

### ISSUE THREAD

**Issue by renesas-adam-benson** [FreeRTOS/FreeRTOS-Libraries-Integration-Tests#43]
Hi, when compiling tests with IAR for ARM v9.20.2 we encounter a compile issue with the following line:

https://github.com/FreeRTOS/FreeRTOS-Libraries-Integration-Tests/blob/7b531a24eb3d1f5e9fdd23ca0f3c57d7f24c875f/src/pkcs11/core_pkcs11_test.c#L377

IAR gives the following error: 

```
"FreeRTOS-Libraries-Integration-Tests/src/pkcs11/core_pkcs11_test.c",377  Error[Pe167]: argument of type "void *" is incompatible with parameter of type "void (*)(void *)"
```

Adding a cast to the line fixes the compile error:

```c
threadHandles[ xTaskNumber ] = FRTest_ThreadCreate((FRTestThreadFunction_t) pvTaskFxnPtr, &( xGlobalTaskParams[ xTaskNumber ] ));
```

**Comment by chinglee-iot** [comment]
Sorry for late reply to this issue. We will take a look at this issue. Thank you for your feedback.

**Comment by ActoryOu** [comment]
Hi @renesas-adam-benson,
Thanks for your contribution!
I created a PR #47 to change the data structure of prvMultiThreadHelper to resolve this compile warning.
Please feel free to feedback if there is any other issue.

Thanks again!

**Comment by awsblake** [comment]
PR https://github.com/FreeRTOS/FreeRTOS-Libraries-Integration-Tests/pull/47 merged. Close this issue.
