### ISSUE TITLE
Bug when testing with PREPROVISIONED RSA

### ISSUE THREAD

**Issue by VanNamDinh** [FreeRTOS/FreeRTOS-Libraries-Integration-Tests#70]
Hello dev team,

I found a bug when testing with prvTestRsaGetAttributeValue and prvTestRsaGetAttributeValueMultiThread.
Here is my setting
1. `#define PKCS11_TEST_PREPROVISIONED_SUPPORT               ( 1 )`
2. `#define PKCS11_TEST_RSA_KEY_SUPPORT                      ( 1 )`
3. `#define CORE_PKCS11_TEST_ENABLED            ( 1 )`

I got an error in https://github.com/FreeRTOS/FreeRTOS-Libraries-Integration-Tests/blob/9b93c5454ec36190b944f6e1d70bee5b798f09e0/src/pkcs11/core_pkcs11_test.c#L1638

This compares CERTIFICATE_VALUE_LENGTH = 949 with the certificate length that I preprovisioned to ROM before. I think it would be wrong because my certificate length will never fix with 949.

Can you take a look at this and whole functions?

**Comment by moninom1** [comment]
Hello @VanNamDinh , 
Thank you for bringing this to our attention! We will take a look at this issue. Thank you for your patience!

**Comment by chinglee-iot** [comment]
@VanNamDinh 
`PKCS11_TEST_RSA_CERTIFICATE` and `PKCS11_TEST_RSA_CERTIFICATE_LENGTH` are added in this PR #71. These two configs are required to be provided in the **test_param_config.h** if verifying RSA preprovision mechanism.

We would like to invite you to help verify this PR by providing `PKCS11_TEST_RSA_CERTIFICATE` and `PKCS11_TEST_RSA_CERTIFICATE_LENGTH` in your **test_param_config.h** and running the test.

**Comment by VanNamDinh** [comment]
@chinglee-iot 

Thanks for your PR. 
I will check and run the test.

**Comment by VanNamDinh** [comment]
@chinglee-iot 

We confirmed that your MR is OK. Thanks!
![image](https://github.com/FreeRTOS/FreeRTOS-Libraries-Integration-Tests/assets/52021577/1a2866d3-a4b3-4bdf-b5b9-caf34077cb9c)

**Comment by chinglee-iot** [comment]
Appreciate your help in reporting this issue and verifying this PR. Let's close the ticket. Feel free to reopen this ticket if any further question or create a new one.
